// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleExam;

namespace SampleExam.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181211064449_SpaceShipVersion")]
    partial class SpaceShipVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleExam.Planet", b =>
                {
                    b.Property<long>("PlanetID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlanetName");

                    b.Property<long>("Population");

                    b.HasKey("PlanetID");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("SampleExam.SpaceShip", b =>
                {
                    b.Property<long>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxCapacity");

                    b.Property<string>("Planet");

                    b.Property<int>("Utilization");

                    b.HasKey("ShipID");

                    b.ToTable("SpaceShip");
                });
#pragma warning restore 612, 618
        }
    }
}
